import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import ClientOnly from "./components/ClientOnly";
import Modal from "./components/modals/Modal";
import RegisterModal from "./components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/modals/LoginModal";
import useAuth from "./hooks/useAuth";
import RentModal from "./components/modals/RentModal";
import UploadPhotos from "./components/modals/UploadPhotos";
import BookingModal from "./components/modals/BookingModal";

export const metadata: Metadata = {
  title: "Home.Guru",
  description: "Generated by create next app",
};

const font = Nunito({
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <BookingModal />
          <RentModal />
          <RegisterModal />
          <LoginModal />
          <UploadPhotos />
          <Navbar />
        </ClientOnly>
        <div className="pb-20 pt-28">
          {children}
        </div>
      </body>
    </html>
  );
}
